version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: vercel
    versions:
    - 21.2.1
    - 21.2.2
    - 21.2.3
    - 21.3.0
    - 21.3.1
    - 21.3.2
    - 21.3.3
    - 22.0.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: next-seo
    versions:
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.22.0
    - 4.23.0
  - dependency-name: copy-webpack-plugin
    versions:
    - 7.0.0
    - 8.0.0
    - 8.1.0
  - dependency-name: "@fortawesome/fontawesome-svg-core"
    versions:
    - 1.2.34
  - dependency-name: "@fortawesome/free-brands-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: "@fortawesome/free-solid-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: "@fortawesome/free-regular-svg-icons"
    versions:
    - 5.15.2
