const legend = {
	audio: '🔊',
	a11y: '♿️',
	bug: '🐛',
	blog: '📝',
	business: '💼',
	code: '💻',
	content: '🖋',
	data: '🔣',
	doc: '📖',
	design: '🎨',
	example: '💡',
	eventOrganizing: '📋',
	financial: '💵',
	fundingFinding: '🔍',
	ideas: '🤔',
	infra: '🚇',
	maintenance: '🚧',
	platform: '📦',
	plugin: '🔌',
	projectManagement: '📆',
	question: '💬',
	review: '👀',
	security: '🛡️',
	tool: '🔧',
	translation: '🌍',
	test: '⚠️',
	tutorial: '✅',
	talk: '📢',
	userTesting: '📓',
	video: '📹',
}

export function getAllContributorsEmoji(key) {
	return legend[key]
}
